# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/catalog')),
                ('slug', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Каталог на главной',
            },
        ),
        migrations.CreateModel(
            name='Category_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/catalog_element')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('full_text', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Category')),
            ],
            options={
                'verbose_name': 'Элемент каталога',
            },
        ),
        migrations.CreateModel(
            name='Goods_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='catalog/')),
            ],
            options={
                'verbose_name': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Offer_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/offer')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Post_wellness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='welness_icons')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('lastname', models.TextField()),
                ('name_middlename', models.TextField()),
                ('passport', models.IntegerField()),
                ('birthday', models.DateField(default='')),
                ('telephone', models.IntegerField(default='')),
                ('region', models.TextField(default='')),
                ('index', models.IntegerField(default='')),
                ('district', models.TextField(default='')),
                ('town', models.TextField(default='')),
                ('street', models.TextField(default='')),
                ('number', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Форма регистрации',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField(default='')),
                ('middle', models.TextField(default='')),
                ('number', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Лидеры',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='refferal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Sponsor'),
        ),
    ]
