# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='images/business_bullet', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'бизнес-проект: буллеты',
                'verbose_name': 'бизнес-проект: буллет',
            },
        ),
        migrations.CreateModel(
            name='BusinessText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('full_text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Бизнес-проект: текст для страниц',
                'verbose_name': 'Бизнес-проект: текст для страницы',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Каталоги',
                'verbose_name': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='CategoryElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('photo', models.ImageField(help_text='Основное фото для каталога. Остальные фото можно разместить в поле "Текст"', upload_to='images/catalog_element', verbose_name='Фото')),
                ('description', models.CharField(help_text='1-2 предложения о продукте', max_length=100, verbose_name='Краткое описание')),
                ('full_text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=True, verbose_name='Показывать в каталоге')),
                ('prepared', models.BooleanField(default=False, verbose_name='Полностью подготовлено')),
            ],
            options={
                'verbose_name_plural': 'Товарные карточки',
                'verbose_name': 'Товарная карточка',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='images/photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'изображения',
                'verbose_name': 'изображение',
            },
        ),
        migrations.CreateModel(
            name='OfferElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='images/offer', verbose_name='Фото')),
                ('description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('to_fix', models.BooleanField(default=False, verbose_name='Закрепить на главной')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акция',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='welness_icons', verbose_name='Фото')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Записи для Wellness',
                'verbose_name': 'Записи для Wellness',
            },
        ),
        migrations.CreateModel(
            name='RecMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, verbose_name='Почтовый ящик')),
            ],
            options={
                'verbose_name_plural': 'Настройки уведомлений: ящики, принимающие заявки',
                'verbose_name': 'Настройки уведомлений: ящики, принимающие заявки',
            },
        ),
        migrations.CreateModel(
            name='SMTPMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта gmail (Пример: example@gmail.com')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
            options={
                'verbose_name_plural': 'Настройки уведомлений: ящик отправки уведомлений',
                'verbose_name': 'Настройки уведомлений: ящик отправки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('slug', models.CharField(default='', max_length=30, verbose_name='Метка(для URl-адреса)')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
                'verbose_name': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('video_url', models.URLField(verbose_name='URL-ссылка')),
            ],
            options={
                'verbose_name_plural': 'Видео',
                'verbose_name': 'Видео',
            },
        ),
        migrations.RemoveField(
            model_name='category_element',
            name='category',
        ),
        migrations.DeleteModel(
            name='Goods_Price',
        ),
        migrations.DeleteModel(
            name='Offer_Element',
        ),
        migrations.DeleteModel(
            name='Post_wellness',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='refferal',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Лидер', 'verbose_name_plural': 'Лидеры'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='number',
        ),
        migrations.AddField(
            model_name='category',
            name='on_index',
            field=models.BooleanField(default=False, verbose_name='Разместить на главной'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='', upload_to='images/catalog', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='code_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Код в Oriflame'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='on_business',
            field=models.BooleanField(default=False, verbose_name="Добавить в список на странице 'Бизнес-проект'"),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='photo',
            field=models.ImageField(default='', upload_to='images/sponsor', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Метка(для URl-адреса)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='middle',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.DeleteModel(
            name='Category_Element',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='categoryelement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryelement',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.Subcategory', verbose_name='Подкатегории'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='category', to='main_site.Subcategory', verbose_name='Подкатегории'),
        ),
    ]
