# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_video_in_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет в разеле "Видео"'),
        ),
    ]
