# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_video_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='refferal_url',
            field=models.CharField(default='', max_length=200, verbose_name='Реферальная ссылка'),
        ),
    ]
