# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_sponsor_refferal_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTPMail',
        ),
    ]
