# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20170713_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(default='', max_length=30, verbose_name='Метка (для URl-адреса)'),
        ),
    ]
