# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20171218_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/catalog', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/sponsor', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='refferal_url',
            field=models.CharField(max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=30, null=True, verbose_name='Метка (для URl-адреса)'),
        ),
    ]
